<!-- Main Example1 View Container-->
<div id="boneyardViewExample1" style="display:none">
    <!-- Example1 Button bar -->
    <div class="horde-buttonbar">
    <ul>
        <li class="horde-icon" id="boneyard-cancel-button"><?php echo Horde::widget(array('title' => _("_Cancel"), 'class' => 'boneyard-delete')) ?></li>
        <li class="horde-icon" id="boneyard-assign-button"><?php echo Horde::widget(array('title' => _("_Assign"), 'class' => 'boneyard-assign')) ?></li>
    </ul>
    </div>
    Example 1 - Default page
</div>
<!-- End of Example1 View Container -->
